name: tahfizh_qu_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.5
  ndialog: ^4.2.0
  shimmer: ^2.0.0
  toast: ^0.2.9
  another_flushbar: ^1.12.29
  future_progress_dialog: ^0.2.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg_provider: ^1.0.3
  stop_watch_timer: 2.0.0
  flutter_sound: 9.2.13
  lottie: 2.1.0
  dropdown_plus: 0.0.9
  permission_handler: 10.2.0
  google_sign_in: 5.4.2
  flutter_signin_button: 2.0.0
  flutter: 
    sdk: flutter
  firebase_core: ^2.4.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/svg/
    - assets/assets/
    - assets/assets/lottie/
  uses-material-design: true

